# Generated by Django 3.2.7 on 2022-05-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'コメント情報', 'verbose_name_plural': 'コメント情報'},
        ),
    ]
